### ISSUE TITLE
Externs issue

### ISSUE THREAD

**Issue by eggsyntax** [gnl/playback#1]
Whee, first issue! Just wanted to let you know:

I added `[com.github.gnl/playback "0.3.9"]` to the project.clj of a Clojure-only project,  and when I require the preload ns from the REPL, I get this error:

```
user> (require 'playback.preload)
Syntax error (ClassNotFoundException) compiling . at (cljs/externs.clj:135:17).
org.kohsuke.args4j.CmdLineException
```

If I add the preload ns to the requires of my user.clj file and send it to the REPL, I get a slightly different error:

```
user> (ns user
        (:require [clojure.pprint]
                  ...
                  [playback.preload]))

Syntax error compiling at (cljs/env.cljc:9:1).
namespace 'cljs.externs' not found
```

(unsurprisingly I don't have an externs file, and don't have cljs or any related libs in project.clj)

**Comment by eggsyntax** [comment]
Requiring it directly from the REPL in a different REPL instance gives me the same error as the 2nd one above (odd that they'd differ, but the 2nd one seems to make more sense anyway 🤷 

```
user>(require 'playback.preload)
Syntax error compiling at (cljs/env.cljc:9:1).
namespace 'cljs.externs' not found
```

**Comment by gnl** [comment]
Given that this is the second issue that popped up _today_ that is solved by simply adding ClojureScript to the deps (as discussed on the Clojurians Slack), I'm inclined to simply say screw it, keep the part of the README that says you need ClojureScript even under Clojure, and decide not to care about dev dependencies or invest time here purely for the sake of doing the right thing. Can you live with that? :)

**Comment by gnl** [comment]
Actually let me try the solution to the first one I was given by jpmonettas, if that fixes it – good, if not – see the comment above.

**Comment by gnl** [comment]
Debux requires ClojureScript as well, so let's take the easy way out here, just add it to the dev deps and try to live with it.

**Comment by eggsyntax** [comment]
> I'm inclined to simply say screw it, keep the part of the README that says you need ClojureScript even under Clojure, and decide not to care about dev dependencies or invest time here purely for the sake of doing the right thing. Can you live with that? :)

Of course! Embarrassingly I overlooked that part of the README 😆

**Comment by gnl** [comment]
> Of course! Embarrassingly I overlooked that part of the README 😆

May not have been in there yet. 😁

**Comment by gnl** [comment]
@eggsyntax apparently ClojureScript's baggage can sometimes cause weird dependency conflicts on Clojure, so I changed my mind about this, dug a little deeper and fixed it both here and in debux.

**Comment by eggsyntax** [comment]
Nice! It was workable to include cljs in the dev deps, but certainly seems better to not require that if possible. Thanks!
